/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
tasks.create<Copy>("copy") {
	description = "Copy src to dst."
	group = "Custom"

	from("src")
	into("dst")
}
